spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message-service/**
          filters:
            - RewritePath=/message-service/(?<path>.*), /$\{path}
server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.int}
    prefer-ip-address: false
    leaseRenewalIntervalInSeconds: 10
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true